const { solveManifold, solveTimelines } = require('./solution');

function assertEqual(actual, expected, label) {
    if (actual === expected) {
        console.log(`PASS: ${label}`);
    } else {
        console.error(`FAIL: ${label} — expected ${expected}, got ${actual}`);
        process.exitCode = 1;
    }
}

// Example from the puzzle description
const example = `\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

assertEqual(solveManifold(example), 21, 'example from puzzle (21 splits)');

// Minimal: S above a single splitter
const single = `\
.S.
...
.^.
...`;
assertEqual(solveManifold(single), 1, 'single splitter hit');

// S above a splitter whose children hit no more splitters
const oneLevel = `\
...S...
.......
...^...
.......`;
assertEqual(solveManifold(oneLevel), 1, 'one splitter, no further splits');

// Two splitters: one below S, two below the first
const twoLevel = `\
...S...
.......
...^...
.......
..^.^..
.......`;
assertEqual(solveManifold(twoLevel), 3, 'three splitters all hit');

// Beam that misses all splitters (wrong column)
const miss = `\
S......
.......
.....^.
.......`;
assertEqual(solveManifold(miss), 0, 'beam misses all splitters');

// Two beams merge and hit the same splitter once
const merge = `\
.S.S...
.......
.......
..^....
.......`;
// Only one S is used per puzzle, but test merging via splitter children:
const mergeViaChildren = `\
...S...
.......
...^...
.......
..^.^..
.......
.^...^.
.......`;
// Split 1: (2,3). Spawn (2,2) and (2,4).
// (2,2) -> hits (4,2). Split 2. Spawn (4,1) and (4,3).
// (2,4) -> hits (4,4). Split 3. Spawn (4,3) and (4,5).
// (4,3) is spawned twice — merges into one beam hitting nothing below.
// (4,1) -> hits (6,1). Split 4.
// (4,5) -> hits (6,5). Split 5.
// Total: 5
assertEqual(solveManifold(mergeViaChildren), 5, 'merge: (4,3) deduped, total 5 splits');

// --- Part 2 tests ---
assertEqual(Number(solveTimelines(example)), 40, 'Part 2 example: 40 timelines');
assertEqual(Number(solveTimelines(single)), 2,  'Part 2 single splitter: 2 timelines (left + right)');
assertEqual(Number(solveTimelines(miss)),   1,  'Part 2 beam misses splitters: 1 timeline (exits)');

// Three splitters all hit: root → left+right → each hits another splitter → each exits 2 ways
// f(0,3)=f(2,2)+f(2,4); f(2,2)=f(4,1)+f(4,3)=1+1=2; f(2,4)=f(4,3)+f(4,5)=1+1=2; total=4
assertEqual(Number(solveTimelines(twoLevel)), 4, 'Part 2 two-level: 4 timelines');

console.log('\nAll tests completed.');
